services:
  api:
    build: ./api
    ports:
      - "5001:5001"
    container_name: novastore_api
    
  client:
    build: ./client
    depends_on:
      - api
    environment:
      - API_URL=http://api:5001
    profiles:
      - exercise  